/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mcoder_jge_g3d_render_Pipeline */

#ifndef _Included_com_mcoder_jge_g3d_render_Pipeline
#define _Included_com_mcoder_jge_g3d_render_Pipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mcoder_jge_g3d_render_Pipeline
 * Method:    clipTriangle
 * Signature: (Lcom/mcoder/jge/g3d/geom/Triangle;[Lcom/mcoder/jge/g3d/geom/Plane;Z)[Lcom/mcoder/jge/g3d/geom/Triangle;
 */
JNIEXPORT jobjectArray JNICALL Java_com_mcoder_jge_g3d_render_Pipeline_clipTriangle
  (JNIEnv *, jobject, jobject, jobjectArray, jboolean);

#ifdef __cplusplus
}
#endif
#endif
